### ISSUE TITLE
cnxml-to-html5: cnxn not transformed

### ISSUE THREAD

**Issue by karenc** [Connexions/rhaptos.cnxmlutils#102]
In the index.cnxml of m0003:

```xml
        alternately. See the plot in the module
            <cnxn
              document='m0004'
              strength='7'
              target='squarewave'
            >Elemental Signals</cnxn>.
          </para>
```

Transformed to html:

```xml
        alternately. See the plot in the module <div class="not-converted-yet">NOT_CONVERTED_YET: cnxn</div><cnxn xmlns:md="http://cnx.rice.edu/mdml/0.4" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns="http://cnx.rice.edu/cnxml" document="m0004" target="squarewave" strength="7">Elemental Signals</cnxn>.
      </p>
```

**Comment by pumazi** [comment]
``cnxn`` isn't a known tag. Is it?

**Comment by karenc** [comment]
It's probably the old name for link.  If we transform it to `<a>` in html then it will transform back to cnxml as `<link>`.  I don't know if the transform is supposed to be correct or if it has to support whatever we have in the database...

For some reason, it's actually transformed in webview.  Have a look at the solution in http://cnx.org/contents/b64b163b-9da8-4458-b943-7ca267109686@16/The_Fundamental_Signal#exer2

**Comment by edwoodward** [comment]
cnxn was a tag we abandoned.  I think the CNXML you are looking at is 
not CNXML 0.7.

**Comment by karenc** [comment]
Oh come to think about it we do have a transform to upgrade cnxml to cnxml 0.7
