### ISSUE TITLE
module-id attribute missing from roundtrip CNXML

### ISSUE THREAD

**Issue by edwoodward** [Connexions/rhaptos.cnxmlutils#111]
I imported some converted CNXML and it gets an error in the Legacy editor because module-id attribute is required and missing. It should be populated with the mXXXXX value from the creation of the module on Legacy.

**Comment by pumazi** [comment]
There is no way to put this in the xslt. The best we can do it put it in within the post-processing logic, which is where the reference resolver runs.

I was under the impression the module-id could be left out, because it's not needed for when legacy reads the file.

**Comment by edwoodward** [comment]
For viewing it might not matter, but it does for editing. A module-id 
with a dummy value might work. I'm not sure the value is used for 
anything, but is just included for completeness. I'll be able to test it 
better once the production instance is up and running.
