### ISSUE TITLE
HTML to CNXML Transform - br is not being converted

### ISSUE THREAD

**Issue by edwoodward** [Connexions/rhaptos.cnxmlutils#113]
I published 2 Pages on beta.cnx.org and both had NOT_CONVERTED_YET: br.  I thought the first one was because I copy and pasted text, but the second one was typed in. The br was an extra line break at the end of the Page.

See http://legacybeta.cnx.org/content/m53198/1.5/?legacy=true

**Comment by karenc** [comment]
There's going to be a new set of issues because I was only transforming html that was generated from cnxml.  This is html from the editor.  For example, `<div data-type="newline"><br/></div>` would be transformed to cnxml `<newline/>` but there's no transformation just for `<br/>`.

**Comment by karenc** [comment]
The html is here: http://betaarchive.cnx.org/contents/12456079-de01-4b69-b1d7-d8302dcb8872@5.html

```xml
<p xmlns="http://www.w3.org/1999/xhtml"
   xmlns:bib="http://bibtexml.sf.net/"
   xmlns:data="http://dev.w3.org/html5/spec/#custom"
   xmlns:epub="http://www.idpf.org/2007/ops"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:lrmi="http://lrmi.net/the-specification"
   ><br/></p>
```
