### ISSUE TITLE
HTML to CNXML Transform - span is not being converted

### ISSUE THREAD

**Issue by edwoodward** [Connexions/rhaptos.cnxmlutils#114]
On beta.cnx.org, I copy and pasted text from a web page to the editor.  It published correctly, but had a NOT_CONVERTED_YET: span in the text on legacybeta.

**Comment by edwoodward** [comment]
See http://legacybeta.cnx.org/content/m53199/1.1/?collection=col10001/1.1&legacy=true

**Comment by karenc** [comment]
The html is here: http://betaarchive.cnx.org/contents/4fcecc4c-cda3-4ee2-9034-65398cc26ace@1.html

Specifically the spans are:

```xml
<span class="add-figure-left">+</span>
```

and

```xml
<span class="add-figure-right">+</span>
```
