### ISSUE TITLE
Processing Instructions are missing when published to Legacybeta

### ISSUE THREAD

**Issue by edwoodward** [Connexions/rhaptos.cnxmlutils#118]
I published a derived copy Introduction Page from A&P on beta.cnx.org. It published successfully on beta.  I then searched for it on legacybeta.cnx.org.  I found it, but the processing instructions are missing.

Original CNXML with processing instructions
![screenshot from 2015-03-09 21 08 58](https://cloud.githubusercontent.com/assets/1394695/6568158/c4aaf840-c6a0-11e4-912c-921ce520afde.png)

Derived copy CNXML where processing Instructions should be
![screenshot from 2015-03-09 21 10 15](https://cloud.githubusercontent.com/assets/1394695/6568163/d6755606-c6a0-11e4-9319-434aa7be2d50.png)

**Comment by pumazi** [comment]
@edwoodward I'm going to need a link to the document.

**Comment by edwoodward** [comment]
Rewrite
http://beta.cnx.org/contents/3b8b507e-af4d-49e7-8d26-b1a61138a7fc@1/Ed's_Introduction

Legacy Beta
http://legacybeta.cnx.org/content/m53215/latest/

**Comment by pumazi** [comment]
Aha! For an unknown reason, the processing instructions in the document you are working on are commented out. (See [the value for 'content'](http://beta.cnx.org/contents/3b8b507e-af4d-49e7-8d26-b1a61138a7fc@1.json)) I am certain that comments are removed during transform. This is why the instructions vanish.

**Comment by pumazi** [comment]
My next step will be to manually enter the content into the database and publish. I'm certain the transforms allow and pass-through processing instructions. So somewhere outside of the transforms is where the commenting out of these is happening. @edwoodward, if you have time you could also do this using curl/wget (or [python-requests](http://docs.python-requests.org/en/latest/)) then try publishing (via the webview interface).

**Comment by edwoodward** [comment]
@pumazi How could they be commented out outside of the transform? The screenshot of the original source shows them not commented out. There is no way to edit them in Rewrite. I guess if Publishing or the editor is doing it it is possible.

**Comment by pumazi** [comment]
I can confirm that the processing instructions are getting commented on save.

**Comment by pumazi** [comment]
Followup at Connexions/webview#953
