### ISSUE TITLE
introduction class missing from HTML

### ISSUE THREAD

**Issue by edwoodward** [Connexions/rhaptos.cnxmlutils#129]
This was reported by Dante.

CNXML for some OSC books has a class="introduction" as part of the document element.  This needs to be preserved in HTML and converted back in CNXML. It is used in the PDF generation and by Tutor.

An example of the CNXML is https://legacy.cnx.org/content/m42119/latest/

       <document xmlns="http://cnx.rice.edu/cnxml" xmlns:md="http://cnx.rice.edu/mdml" id="imported- from-openoffice" module-id="imported-from-openoffice" cnxml-version="0.7" class="introduction">
       <title>Introduction to Science and the Realm of Physics, Physical Quantities, and Units</title>

See https://github.com/Rhaptos/Products.CNXMLTransforms/issues/1

**Comment by pumazi** [comment]
I need to know how this normally gets in the document. Does someone manually enter it in full source editing?

Also, we need to think about how webview/aloha is going to put this on the content. Or are we to assume that every page at the beginning of a book section (aka translucent binder / sub collection) is an introduction?

This doesn't seem like the bests solution. What if the module is used in one book as the introduction and not used that way within another book? The chances of this happening are slim, but still possible.

**Comment by pumazi** [comment]
Is there any chance we can progressively change this from ``@class`` to a ``cnx-pi`` element entry? This would allow webview to enter it on the document without a new interface and allow forward and backward compatibility for pdf production.

**Comment by edwoodward** [comment]
Yes, it is manually entered. It is a hack we used to mark the intro 
modules. It is essentially a processing instruction placed in a class.  
Can we store it as a processing instruction, but put it back as a 
class?  That would solve the editing issue. If they are used out of 
place, it will only be a problem if the user selects the correct print 
style.  It has not happened yet that I know of.

**Comment by edwoodward** [comment]
As I mentioned in an earlier comment, we can store it as a processing 
instruction, but the PDF generation needs it as a class in CNXML right 
now.  When we work on Transformation Services, we can look at fixing it.
