### ISSUE TITLE
University Physics vol. 2: Some index terms not sorting correctly

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/rhaptos.cnxmlutils#167]
### Initial report from Kerwin (fall 2017):

`Power capacitors` sorts to the top of the page. `Klein bottle` is under `Symbols`.

found on https://staging.cnx.org/contents/eg-XcBxE@4.1:7rpOXKcg@4.1/Index and https://cnx.org/contents/eg-XcBxE@5.1:7rpOXKcg@5.1/Index

### Analysis from Ross:
https://cnx.org/contents/JOs6racw@2/RLC-Series-Circuits-with-AC

"Power Capacitors" is a term in the caption of a figure. However, the text is actually <span data-type="term"> Power Capacitors</span> - there's a leading "space", however the CNXML source does not have a space in the term. Same for "Klein bottle", even to the point of it being inside a figure caption. (though I'm not sure why that one ended up as a Symbol, while "Power Capacitors" did not.)

So, this looks to be a CNXML -> HTML bug.

![indexbug](https://user-images.githubusercontent.com/7863733/41922135-0db07878-792a-11e8-9089-1acacf496328.png)

**Comment by brittweinstein** [comment]
Issue moved to [Connexions/content-managers #189](https://github.com/Connexions/content-managers/issues/189) via [**ZenHub**](https://www.zenhub.com/)
