### ISSUE TITLE
Glossaries are not converted to HTML

### ISSUE THREAD

**Issue by edwoodward** [Connexions/rhaptos.cnxmlutils#49]
Modules are missing Glossaries once they are converted to HTML.

http://cnx.org/content/m42792/latest/?collection=col11407/1.7
http://cnx.org/contents/afe4332a-c97f-4fc4-be27-4e4d384a32d8@7.14:5

http://cnx.org/content/m42794/1.3/?collection=col11407/1.7
http://cnx.org/contents/afe4332a-c97f-4fc4-be27-4e4d384a32d8@7.14:4

**Comment by pumazi** [comment]
Fixed in https://github.com/Connexions/rhaptos.cnxmlutils/pull/66
