### ISSUE TITLE
Lists are not being converted correctly

### ISSUE THREAD

**Issue by edwoodward** [Connexions/rhaptos.cnxmlutils#55]
List in Introductory Statistics is not converting at all. Look for Collaborative Statistics note in links below

Webview: http://cnx.org/contents/30189442-6998-4686-ac05-ed152b91b9de@17.20:12
Legacy: http://cnx.org/content/m46930/1.3/?collection=col11562/1.17

**Comment by karenc** [comment]
The inline list in exercise "For the following 11 salaries, calculate the IQR and determine if any salaries are outliers. The salaries are in dollars." is displaying with semi-colons as item separators on dev:
http://dev.cnx.org/contents/introductory_statistics:12/Introductory_Statistics

The list just above section titled "Short-Run Outcomes for Perfectly Competitive Firms" is displaying correctly on dev:
http://dev.cnx.org/contents/69619d2b-68f0-44b0-b074-a9b2bf90b2c6@10.1:37/Principles_of_Economics

The list in "Integrated Concepts" is displaying correctly on dev:
http://dev.cnx.org/contents/college_physics:144/College_Physics

@edwoodward Is this issue fixed?
