### ISSUE TITLE
HTML to CNXML Transform - Section losing type and class

### ISSUE THREAD

**Issue by edwoodward** [Connexions/rhaptos.cnxmlutils#83]
I tested a module from Physics and noticed the sections were missing the class and type which is very important for PDF generation.

Correct markup:
`<section id="fs-id1546211" class="conceptual-questions" type="conceptual-questions">`

Converted Markup:
`<section id='fs-id1546211'>`

**Comment by karenc** [comment]
I found the same problem when I was checking through the modules in "College Physics".  I already have a [commit](https://github.com/Connexions/rhaptos.cnxmlutils/commit/a93fb65e0ac7883575c1331eaea06c93e2b9f25e) to fix the "type" attribute.  What I'm not sure about is the "class" attribute.  I checked http://cnx.org/eip-help/section and it doesn't mention "class" so I thought it's ok to drop it.  Should we always copy the "class" attribute for all the tags?

**Comment by edwoodward** [comment]
Module used for testing was "Discovery of the Atom"

http://legacy.cnx.org/content/m42589/latest/source

**Comment by edwoodward** [comment]
Class can be added to any CNXML element.  It is used in the OSC PDDF generation.

**Comment by karenc** [comment]
Ok, thanks for the confirmation.  I'll copy the class attribute on all the tags.

**Comment by edwoodward** [comment]
I think we should copy it.  it will not be there unless someone went to the trouble to add it.
