### ISSUE TITLE
html5-to-cnxml: Footnote id required

### ISSUE THREAD

**Issue by karenc** [Connexions/rhaptos.cnxmlutils#86]
I'm not completely sure what the footnote id is for, but according to http://cnx.org/eip-help/footnote, id is required.

**Comment by edwoodward** [comment]
Most likely for linking to the footnote.

**Comment by karenc** [comment]
I have looked for the id and it's not anywhere else in the book.  For example:

``` 
$ grep -r '2598220' col11406_1.8_complete/*/index.cnxml
col11406_1.8_complete/m42678/index.cnxml:</m:math><footnote id="eip-id2598220">Values are approximate, are not directly observable, and vary with model.</footnote> 
```
